codey:
  token: change-me
  roles:
    - CodeyRole
    - CodeyBoss
  embedColor: "#f1c40f"
logging:
  level:
    io.horrorshow.codey: debug
  file:
    name: ./logs/codey.log
spring:
  main:
    web-application-type: none
wandbox:
  url: https://wandbox.org/api/compile.json
  compiler:
    java: openjdk-head
    c: gcc-head-c
    cpp: gcc-head
    cs: mono-head
    erlang: erlang-head
    elixir: elixir-head
    haskell: ghc-head
    d: dmd-head
    rust: rust-head
    py: pypy-head
    python: cpython-3.8.0
    ruby: ruby-head
    scala: scala-2.13.x
    groovy: groovy-head
    javascript: nodejs-head
    js: nodejs-head
    coffee: coffeescript-head
    swift: swift-head
    perl: perl-head
    php: php-head
    lua: luajit-head
    sqlite: sqlite-head
    pascal: fpc-head
    lisp: sbcl-head
    vim: vim-head
    ocaml: ocaml-head
    go: go-head
    bash: bash
    pony: pony-head
    crystal: crystal-head
    nim: nim-head
    openssl: openssl-head
    fs: fsharp-head
    cmake: cmake-head
    r: r-head
    ts: typescript-3.9.5
    typescript: typescript-3.9.5
piston:
  use-local: true
  execute-url: https://emkc.org/api/v2/piston/execute
  runtimes-url: https://emkc.org/api/v2/piston/runtimes
  local-execute-url: http://localhost:2000/api/v2/execute
  local-runtimes-url: http://localhost:2000/api/v2/runtimes
